server:
  port: 8086

spring:
  application:
    name: ms-consumidor-horarios

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  session-token: ${AWS_SESSION_TOKEN}
  region: ${AWS_REGION:us-east-1}

