server:
  port: 8080

spring:
  application:
    name: bff-transporte

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AZURE_AD_B2C_TENANT:TransporteDuoc}.b2clogin.com/${AZURE_AD_B2C_TENANT:TransporteDuoc}.onmicrosoft.com/${AZURE_AD_B2C_POLICY:B2C_1_susi}/v2.0/
          jwk-set-uri: https://${AZURE_AD_B2C_TENANT:TransporteDuoc}.b2clogin.com/${AZURE_AD_B2C_TENANT:TransporteDuoc}.onmicrosoft.com/${AZURE_AD_B2C_POLICY:B2C_1_susi}/discovery/v2.0/keys

microservices:
  vehiculos:
    url: ${MS_VEHICULOS_URL:http://localhost:8081}
  rutas:
    url: ${MS_RUTAS_URL:http://localhost:8082}

logging:
  level:
    com.transporte: DEBUG
    org.springframework.security: DEBUG
