server:
  port: 8080

spring:
  application:
    name: bff-transporte

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://transporteduoc.b2clogin.com/49d457bf-27e6-40e2-b09e-c6b5ecc6e07b/v2.0/
          jwk-set-uri: https://transporteduoc.b2clogin.com/TransporteDuoc.onmicrosoft.com/B2C_1_susi/discovery/v2.0/keys

microservices:
  vehiculos:
    url: ${MS_VEHICULOS_URL:http://localhost:8081}
  rutas:
    url: ${MS_RUTAS_URL:http://localhost:8082}

logging:
  level:
    com.transporte: DEBUG
    org.springframework.security: DEBUG
